/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.java_swing_project.main.java.view.booking;

import com.java_swing_project.main.java.domain.Booking;
import com.java_swing_project.main.java.service.BookingService;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

/**
 *
 * @author huy
 */
public class BookingTable extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BookingTable.class.getName());
    private BookingService bookingService;
    /**
     * Creates new form BookingTable
     */
    public BookingTable() {
        bookingService = new BookingService();
        initComponents();
        setSize(700,500);
        setVisible(true);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        String[] columns = {"Id", "Pet id", "Service id","Room id", "Create Time", "End Time", "Note"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);
        List<Booking> bookings = this.bookingService.getAllBookingFromDb();

        for (Booking bk : bookings) {
            model.addRow(new Object[] {bk.getId(),bk.getPetId(),bk.getServiceId(),
                    bk.getRoomId(), bk.getCreateTime(),bk.getEndTime(), bk.getNote()});
        }
        booking_table.setModel(model);

        reloadBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String[] columns = {"Id", "Pet id", "Service id","Room id", "Create Time", "End Time", "Note"};
                DefaultTableModel model = new DefaultTableModel(columns, 0);
                List<Booking> bookings = bookingService.getAllBookingFromDb();

                for (Booking bk : bookings) {
                    System.out.println(bk);
                    model.addRow(new Object[] {bk.getId(),bk.getPetId(),bk.getServiceId(),
                            bk.getRoomId(), bk.getCreateTime(),bk.getEndTime(), bk.getNote()});
                }
                booking_table.setModel(model);
            }
        });

        deleteBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int row = booking_table.getSelectedRow();
                if (row == -1) {
                    JOptionPane.showMessageDialog(booking_table, "Vui long chon booking truoc !");
                } else {
                    int confirm = JOptionPane.showConfirmDialog(booking_table, "Ban chac chan muon xoa khong !");

                    if (confirm == JOptionPane.YES_OPTION) {
                        int id = Integer.valueOf(String.valueOf(booking_table.getValueAt(booking_table.getSelectedRow(), 0)));
                        System.out.println(id);
                        bookingService.getBookingDelete(id);
                    }
                }
            }
        });

        updateBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // todo : wait for pet table
                int row = booking_table.getSelectedRow();
                if (row == -1) {
                    JOptionPane.showMessageDialog(booking_table, "Vui long chon booking truoc !");
                } else {
                    int id = Integer.valueOf(String.valueOf(booking_table.getValueAt(booking_table.getSelectedRow(), 0)));
                    System.out.println(id);
                    new UpdateBooking(id);
                }
            }
        });

        goBackBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //todo : wait for dashboad
            }
        });

        createBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //todo : wait for invoice Table
                int row = booking_table.getSelectedRow();
                if (row == -1) {
                    JOptionPane.showMessageDialog(booking_table, "Vui long chon booking truoc !");
                } else {
                    int id = Integer.valueOf(String.valueOf(booking_table.getValueAt(booking_table.getSelectedRow(), 0)));
                    System.out.println(id);
                }
            }
        });


    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        booking_table = new javax.swing.JTable();
        reloadBtn = new javax.swing.JButton();
        createBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        goBackBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        booking_table.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(booking_table);

        reloadBtn.setText("Reload");
        reloadBtn.addActionListener(this::reloadBtnActionPerformed);

        createBtn.setText("Create invoice");
        createBtn.addActionListener(this::createBtnActionPerformed);

        updateBtn.setText("Update");
        updateBtn.addActionListener(this::updateBtnActionPerformed);

        deleteBtn.setText("Delete");

        goBackBtn.setText("Go Back");
        goBackBtn.addActionListener(this::goBackBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(reloadBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(createBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(updateBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(deleteBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(goBackBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteBtn)
                    .addComponent(goBackBtn)
                    .addComponent(updateBtn)
                    .addComponent(createBtn)
                    .addComponent(reloadBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reloadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reloadBtnActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateBtnActionPerformed

    private void goBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goBackBtnActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            // Thiết lập giao diện giống hệ điều hành đang chạy
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BookingTable().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable booking_table;
    private javax.swing.JButton createBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton goBackBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton reloadBtn;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
